# Generated by Django 5.0.6 on 2024-06-23 13:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                ("content", models.TextField()),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 6, 23, 13, 54, 0, 276726, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("last_update_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "Draft"), ("PB", "Published")],
                        default="PB",
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-publish_date",),
                "indexes": [
                    models.Index(
                        fields=["-publish_date"], name="blog_post_publish_7e8b08_idx"
                    )
                ],
            },
        ),
    ]
