# Generated by Django 5.0.6 on 2024-06-24 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_publish_date_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.CharField(
                choices=[("AC", "Active"), ("DB", "Disabled")],
                default="AC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 24, 9, 5, 43, 223229, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
