# Generated by Django 5.0.6 on 2024-06-25 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_tags_alter_post_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 25, 11, 12, 14, 57091, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
